# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eac121852c5456ecc26888eba2837e77e8ac124b0d6c51534c26746cb7cb6aecadb8fa2afc75c4fa8651aa88320504aa7768aed27210e36c7905f274128b96fe

test:
  secret_key_base: 6a4d96d5b67b6e28dc04559df8a91140ffb072478dbb9608a78d7c364d08bf0e943c1d612307f04aacac8dc35a3cd21c7e85716cfa993e0f9e8904ca8a120124

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
